spring:
  application:
    name: fat-brain-api
  datasource:
    url: jdbc:mysql://localhost:3306/fat_brain
    username: root
    password: 2124
    driver-class-name: com.mysql.cj.jdbc.Driver

auth:
  access:
    secret: 6HGcXi+vA9o3AEygwsv2tt4nkZAIZSJb9uqlj17nzsw=
    expires-in: 1800
  refresh:
    secret: 3qG/uZ2omjFQplnNswApwsGl7XVr8fcZLz4rfCHPuqc=
    expires-in: 604800

server:
  port: 80